services:
  - type: web
    name: line-reminder-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --timeout 120 --workers 1
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: TIMEZONE
        value: Asia/Taipei
